### ISSUE TITLE
Validation failed with invalid MIME type

### ISSUE THREAD

**Issue by anykeyh** [kevindew/openapi3_parser#18]
Hello and nice work on this gem !

However, I'm trying to parse swagger file outputted with this kind of MIME types defined:

```
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/SomeDataTypeHere"
              }
            }
```

This gem will crash (validation failed raised) when trying to access the content of `requestBody` because this MIME type doesn't fit with the regexp defined in: lib/openapi3_parser/validators/media_type.rb

I've patched it like this:

```
    ::Openapi3Parser::Validators::MediaType::REGEX = %r{
      \A
      (\w+|\*)+ # word or asterisk
      / # separating slash
      ([-+.\w]+|\*)+ # word (with +, - & .) or asterisk
      \Z
    }x.freeze
```

I'm not sure if that a problem with the gem OR if the swagger file provided is not OpenApi compliant.
Tell me if you want me to create a PR :+1:

**Comment by kevindew** [comment]
Hello @anykeyh - thanks for reporting this. It looks an interesting problem, I've not seen `application/*+json` as a mime type before. I'm finding it tricky to find out much about it and it's prevalence. I've done some digging to try determine if it's valid or not.

Looking at the [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#request-body-object) they reference the field to be a [media type](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#mediaTypes) or a [media range](https://tools.ietf.org/html/rfc7231#appendix-D), with media range being rather cryptically defined as `media-range = ( "*/*" / ( type "/*" ) / ( type "/" subtype ) ) *( OWS    ";" OWS parameter )` which I think rules out `application/*+json` as being valid since it is neither "/*" or a [subtype](https://tools.ietf.org/html/rfc6838#section-4.2). I also checked the schemas that ship with OpenAPI Specification but they seem to lack any validation on whether request bodies have a valid media type or not: https://github.com/OAI/OpenAPI-Specification/blob/f8449d1a893cc6a811c6f3d87e88b05761dc5397/schemas/v3.0/schema.json#L1260-L1265.

Where are you seeing this come from? I saw this [Stack Overflow post](https://stackoverflow.com/questions/48277752/is-application-json-a-valid-accept-header-in-http) that indicates it's provided by the Spring Framework which might indicate this approach is in the wild 🤔 

Thanks for sharing your approach to resolving it 👍 I can see how that fixed it, I think that might be a bit over forgiving as it'd probably accept wrong inputs like `***/***` or `application/text*json`.

**Comment by anykeyh** [comment]
The schema I get come from a supplier for my current professional project, I can't tell you more as I'm bound with strict confidential policies. 
I'm not 100% sure about the technology they use for their API server, but I would put my guess over .NET or Java framework.

One thing I've noticed is they provide multiple MIME type for their endpoints as example below:

```json
          "content": {
            "application/json-patch+json": {
              "schema": {
                "$ref": "#/components/schemas/xxx"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/xxx"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/xxx"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/xxx"
              }
            }
          }
```

In case I try to access the key `application/json`, validation code is called and it raises the exception. Another solution that would work in my case might be to validate over the key you're trying to access instead of the whole `content` block.

And, indeed my solution is a quickfix, probably not strict enough as it would validate invalid data type.

**Comment by kevindew** [comment]
Great, thanks for sharing those details. I think I'm going to consider that to be an invalid mime type and thus not meeting the specification. If you're able to establish otherwise (perhaps raising an issue on https://github.com/OAI/OpenAPI-Specification) I'm quite happy to consider changing this.

This seems like evidence for a feature I've long considered where it [allows a lenient mode for parsing](https://github.com/kevindew/openapi3_parser/blame/main/TODO.md#L19-L20) where it only blows up if types are incorrect (for example any string would be accepted here but not a number). Though I've got a few more changes to make to this before that so that might not be until after OpenAPI 3.1 is out.

It might be best that you carry on using your quickfix in the meantime, particularly if you aren't able to persuade the author of the openapi file to change the media-type definition (which, in my opinion, would be the ideal approach).

Hope this helps.
